### ISSUE TITLE
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node.

### ISSUE THREAD

**Issue by patientx** [DakeQQ/F5-TTS-ONNX#10]
(venv) D:\F5-TTS>python F5-TTS-ONNX-Inference.py
Building prefix dict from the default dictionary ...
Loading model from cache D:\idm-temp\temp\jieba.cache
Loading model cost 0.458 seconds.
Prefix dict has been built successfully.

Run F5-TTS by ONNX Runtime.
NFE_STEP: 0
2024-11-28 00:11:27.9287186 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Mul node. Name:'/f5_transformer/transformer_blocks.0/attn/Mul_15' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:560 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2048 by 2855

Traceback (most recent call last):
  File "D:\F5-TTS\F5-TTS-ONNX-Inference.py", line 175, in <module>
    noise = ort_session_B.run(
  File "D:\F5-TTS\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 266, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/f5_transformer/transformer_blocks.0/attn/Mul_15' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:560 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2048 by 2855

I have an AMD rx 6600, using windows 10. Only changed the model directories etc. Encountering this error. It only worked one time and it was using cpu, but at least I was able to get correct generation. After that always this error. 

Can you also provide correct modifications to the .py for my amd gpu using onnx ?

**Comment by DakeQQ** [comment]
The main issue is that your audio input exceeds the maximum length defined in the exported ONNX model settings. Specifically, MAX_SIGNAL_LENGTH = 2048 (set at line 68 in Export_F5.py), while your audio, after the STFT process, has a length of 2855. Please re-export all ONNX models with an appropriately larger value for MAX_SIGNAL_LENGTH and try more once.

**Comment by patientx** [comment]
> I am not familiar with AMD GPUs, but you might want to search for blogs or official guides on your own. These websites could be helpful. Good luck!
> 
> * https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-onnx.html
> * https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html
> * https://huggingface.co/docs/optimum/onnxruntime/usage_guides/amdgpu
> * https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html  (Windows, use DirectML call the AMD GPU)
> * [How can use onnx model for inference with AMD GPU in Windows? microsoft/onnxruntime#19061](https://github.com/microsoft/onnxruntime/issues/19061)
> * https://pypi.org/project/onnxruntime-directml/

ok, was able to convert onnx models with different MAX_SIGNAL_LENGTH and now want to quantize them to fp16. 
When I run python fp16.py inside the "D:\F5-TTS-ONNX\Do_Quantize\Dynamic_Quant" folder with these changes inside fp16.py

# Path Setting
original_folder_path = r"D:/sd/models/f5-tts-onnx/s"
quanted_folder_path = r"D:/sd/models/f5-tts-onnx/s/q"
model_path = os.path.join(original_folder_path, "F5_Transformer-4096.onnx") 
quanted_model_path = os.path.join(quanted_folder_path, "F5_Transformer-4096-q.onnx") 

The process gives this error, 

Traceback (most recent call last):
  File "D:\F5-TTS-ONNX\Do_Quantize\Dynamic_Quant\fp16.py", line 48, in <module>
    model=onnx.load(quanted_model_path),
  File "D:\F5-TTS\venv\lib\site-packages\onnx\__init__.py", line 212, in load_model
    model = _get_serializer(format, f).deserialize_proto(_load_bytes(f), ModelProto())
  File "D:\F5-TTS\venv\lib\site-packages\onnx\__init__.py", line 149, in _load_bytes
    with open(f, "rb") as readable:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/sd/models/f5-tts-onnx/s/q\\F5_Transformer-4096-q.onnx'

which is understandable because we don't have a quantized model yet ? what should I change here ?

**Comment by DakeQQ** [comment]
Try to using this script instead. I will update the F5-TTS-Do_Quantize later.
```
import os
import gc
import sys
import onnx
import torch
import onnx.version_converter
from onnxslim import slim
from onnxconverter_common import float16
from onnxruntime.transformers.optimizer import optimize_model
from transformers import AutoModelForCausalLM


# Path Setting
original_folder_path = r"C:\Users\Downloads\Model_ONNX"                          # The original folder.
quanted_folder_path = r"C:\Users\Downloads\Model_ONNX_Quanted"                   # The quanted folder.
model_path = os.path.join(original_folder_path, "Model.onnx")                    # The original fp32 model path.
quanted_model_path = os.path.join(quanted_folder_path, "Model_quanted.onnx")     # The quanted model stored path.
download_path = None                        # Set the folder path where the LLM whole project downloaded, otherwise set "NONE".
use_gpu = True                                                                   # If true, the transformers.optimizer will remain the FP16 processes.
provider = 'CPUExecutionProvider'                                                # ['CPUExecutionProvider', 'CUDAExecutionProvider', 'CoreMLExecutionProvider']


# Convert the fp32 to fp16
model = onnx.load(model_path)
model = float16.convert_float_to_float16(model,
                                         min_positive_val=1e-7,
                                         max_finite_val=65504,
                                         keep_io_types=False,        # True for keep original input format.
                                         disable_shape_infer=False, # False for more optimize.
                                         op_block_list=['DynamicQuantizeLinear', 'DequantizeLinear', 'Resize'],  # The op type list for skip the conversion. These are known unsupported op type for fp16.
                                         node_block_list=None)      # The node name list for skip the conversion.
onnx.save(model, quanted_model_path)
model_size_bytes = sys.getsizeof(model.SerializeToString())
model_size_gb = model_size_bytes * 9.31322575e-10  # 1 / (1024 * 1024 * 1024)
if model_size_gb > 2.0:
    is_large_model = True
else:
    is_large_model = False
del model
gc.collect()


# ONNX Model Optimizer
slim(
    model=quanted_model_path,
    output_model=quanted_model_path,
    no_shape_infer=False,   # True for more optimize but may get errors.
    skip_fusion_patterns=False,
    no_constant_folding=False,
    save_as_external_data=is_large_model,
    verbose=False
)

# Upgrade the Opset version. (optional process)
model = onnx.load(quanted_model_path)
model = onnx.version_converter.convert_version(model, 21)
onnx.save(model, quanted_model_path, save_as_external_data=is_large_model)

# It is not recommended to convert an FP16 ONNX model to the ORT format because this process adds a Cast operation to convert the FP16 process back to FP32.
```

**Comment by patientx** [comment]
I know this is another matter but, I found another model with my native language and wanted to use it but when I try to convert it to ONNX format using export.py as I did with the default model that came with f5-tts, I am getting these errors :

```
Start to Export the F5-TTS Preprocess Part.
Traceback (most recent call last):
  File "D:\F5-TTS-ONNX\Export_ONNX\F5_TTS\Export_F5.py", line 268, in <module>
    f5_model = load_model(F5_safetensors_path)
  File "D:\F5-TTS-ONNX\Export_ONNX\F5_TTS\Export_F5.py", line 197, in load_model
    return load_checkpoint(model, ckpt_path, 'cpu', use_ema=True)
  File "D:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 168, in load_checkpoint
    model.load_state_dict(checkpoint["model_state_dict"])
  File "D:\F5-TTS\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
        Missing key(s) in state_dict: "mel_spec.mel_stft.spectrogram.window", "mel_spec.mel_stft.mel_scale.fb".
        size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2555, 512]) from checkpoint, the shape in current model is torch.Size([2546, 512]).
```

The model is from here https://huggingface.co/marduk-ra/F5-TTS-Turkish. I downloaded both .safetensors and vocab.txt and using them as inputs yet getting these errors.

**Comment by DakeQQ** [comment]
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))
Apologies for the delayed response; it's morning now in our timezone (+8).
This error arises from the audio input format. Both parts A and C, in addition to part B, need to be converted to fp16. The format check occurs during the loading of model A, and it will automatically convert the audio to fp16 if 'Float16' is detected.
Inference.py, line 154:
```
if "float16" in model_type:
   audio = audio.astype(np.float16)
```

**Comment by DakeQQ** [comment]
To export the specific F5 version, please download the latest F5-TTS-ONNX release. I have made some adjustments. After downloading, replace the `vocab.txt` file with your own. The path to the `vocab.txt` file is:

```
/F5-TTS-main/data/Emilia_ZH_EN_pinyin/vocab.txt
```

It should works, enjoy : )

**Comment by patientx** [comment]
The latest version is changing something in "F5-TTS\src\f5_tts\infer\utils_infer.py" and it always gives this error : 

```
(venv) D:\F5-TTS-ONNX\Export_ONNX\F5_TTS>python Export_F5.py
Traceback (most recent call last):
  File "D:\F5-TTS-ONNX\Export_ONNX\F5_TTS\Export_F5.py", line 58, in <module>
    from f5_tts.infer.utils_infer import load_checkpoint
  File "D:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 168
    model.load_state_dict(checkpoint["model_state_dict"], , strict=False)
```

Even if I change that line or completely redownload that file from the source it always changes back to this state and gives the error.

The original file doesn't contain that, instead this whole section gets added when I run export

```
        # patch for backward compatibility, 305e3ea
        # for key in ["mel_spec.mel_stft.mel_scale.fb", "mel_spec.mel_stft.spectrogram.window"]:
        #     if key in checkpoint["model_state_dict"]:
        #         del checkpoint["model_state_dict"][key]

        model.load_state_dict(checkpoint["model_state_dict"], , strict=False)
    else:
        if ckpt_type == "safetensors":
            checkpoint = {"model_state_dict": checkpoint}
        model.load_state_dict(checkpoint["model_state_dict"])
```

**Comment by DakeQQ** [comment]
Sorry, It seems too more "," here.
`model.load_state_dict(checkpoint["model_state_dict"], , strict=False)`
It should be "`model.load_state_dict(checkpoint["model_state_dict"], strict=False)`"

**Comment by patientx** [comment]
Yes , I found out your utils_infer include that and after I posted this, updated the file , tried again ... Unfortunately 

```
Start to Export the F5-TTS Preprocess Part.
Traceback (most recent call last):
  File "D:\F5-TTS-ONNX\Export_ONNX\F5_TTS\Export_F5.py", line 270, in <module>
    f5_model = load_model(F5_safetensors_path)
  File "D:\F5-TTS-ONNX\Export_ONNX\F5_TTS\Export_F5.py", line 199, in load_model
    return load_checkpoint(model, ckpt_path, 'cpu', use_ema=True)
  File "D:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 168, in load_checkpoint
    model.load_state_dict(checkpoint["model_state_dict"], strict=False)
  File "D:\F5-TTS\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
        size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2555, 512]) from checkpoint, the shape in current model is torch.Size([2546, 512]). 
```

**Comment by DakeQQ** [comment]
Use your custom vocab.txt (with 2555 words).

The path is: `/F5-TTS-main/data/Emilia_ZH_EN_pinyin/vocab.txt`, Go to that folder and replace it.

**Comment by patientx** [comment]
Finally did it, and the tests are successful as well. Thanks a lot ! I am not actually a developer but trying to share my knowledge with using amd gpu's with various ai applications. I really appreciate what you are doing here, keep up the good work ! And have a nice day.
