### ISSUE TITLE
TRT-LLM

### ISSUE THREAD

**Issue by Bigfishering** [DakeQQ/F5-TTS-ONNX#2]
have u tried to accelerate inference with TensorRT-LLM？or other inference engine of llm to accelerate it？

**Comment by DakeQQ** [comment]
We haven't conducted acceleration tests on desktop computers as our focus is on processing acceleration for Android mobile devices. However, some users have reported positive acceleration results using AMD-GPU with ONNXRuntime and DmlExecutionProvider. I believe similarly good results can be achieved with ORT using CUDAExecutionProvider, TensorRTExecutionProvider, or other inference engines.
