### ISSUE TITLE
Any samples？

### ISSUE THREAD

**Issue by endink** [DakeQQ/F5-TTS-ONNX#5]
是否有推理的示例代码，CPP？

**Comment by DakeQQ** [comment]
目前我们暂无推出 C++ 版本示例的计划，因为 F5-TTS 的计算量已经大到现有的Android 旗艦设备无法满足实时性的要求。若您对 ONNX Runtime (ORT) Python 推理示例感兴趣，可以参考 Export_F5.py 文件中的第 395 行至第 484 行代码。这部分内容提供了如何使用 ORT-Python API 进行F5-TTS模型推理的具体示例。接著，再使用ChatGPT协助您将ORT-Python示例转换至ORT-CPP。

**Comment by endink** [comment]
因为android 慢，这项目不会维护了？我还打算 windows 下测试一下效果，CPP 既然都测试过了又不提供参考代码，这....端侧部署看来只有回归模型方便点

**Comment by DakeQQ** [comment]
感谢您的反馈。我们深知每个用户需求的重要性，但鉴于资源限制，我们目前专注于确保Android设备上的最佳体验。尽管我们已内部测试过F5-TTS-ORT-C++代码，但分享所有内部资源并非我们的义务。我们鼓励您基于现有的Python示例自行转换，这也是开发人员应具备的素质和能力之一。期待您在Windows平台上取得佳绩，并欢迎分享您的成果。感谢您的理解和支持！
