### ISSUE TITLE
TypeError: STFT_Process.istft_A_forward() missing 1 required positional argument: 'phase'

### ISSUE THREAD

**Issue by Bigfishering** [DakeQQ/F5-TTS-ONNX#6]
后处理部分导出时候出错

vocos不是默认会做反傅里叶变换吗？为什么这里是自己做的，然后这个地方的相位和幅度是多少，我看vocos解码出来的结果是（1，xxxx）这样的shape的，传 *denoised 进去好像没解包出幅度和相位的值？

**Comment by DakeQQ** [comment]
您说的没错，Vocos 的源代码中确实会自行调用反傅里叶变换（`torch.nn.functional.istft()`）。然而，这个算子直到当前的 `ONNX Runtime 1.20.0` 版本为止，都不支持导出。这意味着，我们需要用其他算子来替代 `torch.istft()`。因此，在处理 Vocos 源代码时，我们跳过了其后处理部分，并采用了自定义的 `custom.istft(model_type='istft_A')` 函数。具体的实现细节可以在 `Export_ONNX/F5_TTS/STFT_Process.py` 文件的第 108-116 行找到。

根据最新的 `Swivid/F5-TTS-2024/11/11-22:00` 下载版本，`Export_F5.py` 文件依然能够成功导出模型且没有报错。代码 `denoised = self.vocos.decode(denoised)` 输出的是一组 `tuple`，其形状为 `[(1, 513, SIGNAL_LENGTH), (1, 513, SIGNAL_LENGTH)]`。这表示输出包含了两个部分：一个是幅度，另一个是相位。随后，代码 `denoised = self.custom_istft(*denoised)` 接收这两个部分（幅度与相位）作为输入，输出反转换完成的 PCM 音频码流。

期待您提供更详细的错误信息，将有助于我们更快地定位并解决您的问题。

**注：** 导出完成后，请记得重新执行 `pip uninstall vocos` 和 `pip install vocos`，以便恢复安装原始版本的代码。这样做可以避免后续开发或测试过程中可能出现的任何不必要的冲突。
