### ISSUE TITLE
ort-gpu的推理速度比源码中pytorch的推理还要慢？

### ISSUE THREAD

**Issue by Bigfishering** [DakeQQ/F5-TTS-ONNX#7]
这是为什么，即使我用Tensorrt推理，也不如pytorch推理速度快

**Comment by Bigfishering** [comment]
是因为我们的32次推理吗？源码中32次推理是怎么做的？我只知道trt中如果32次推理，需要频繁的做host和device之间的memcpy，这比较耗时间

**Comment by Bigfishering** [comment]
我们有没有办法把这32次迭代放到网络中导出成onnx呢？感觉单次计算导出为onnx，然后onnx执行迭代执行32次抑制了效率

**Comment by DakeQQ** [comment]
感谢您的反馈，我们也注意到 F5-TTS-ONNX 的性能低于 F5-TTS-PyTorch。经过分析，我们发现以下几点：

首先，我们曾尝试直接导出包含32步推理的模型版本，但遇到了以下问题：
1. 图网络结构过大，无法在 Netron 中打开（32 步，每步有 22 层 Transformer）。
2. 使用 onnxsim 或 transformers.optimizer 时，内存消耗巨大，几乎无法使用。
3. 在量化过程中，出现了重复量化的错误。

接下来，我们验证了频繁切换 HOST 与 DEVICE 是否会影响性能：
1. F5-TTS 的 Transformer 参数量仅相当于不到 2B 的 LLM，尽管 RAM 带宽速度可能影响性能，但不应导致如此明显的延迟。
2. 在纯 CPU 模式下，没有切换操作，速度仍明显慢于 PyTorch。
3. 测试了一个简单的自定义矩阵乘法，并对比了模型内部的连续计算与 for 循环计算的耗时差异。测试结果表明，虽然有影响，但减速的幅度并不像预期的那么大。

根据上述分析，我们认为 CPU-GPU 通信并不是性能瓶颈的主要原因。

最后，我们分析了算子耗时，发现最耗时的部分位于 `Export_ONNX/F5_TTS/modeling_modified/F5/modules.py` 文件的第 348-349 行：
```python
x = torch.matmul(torch.softmax(torch.matmul(query, key), dim=-1), value).transpose(1, 2).reshape(2, -1, self.hidden_size)
return attn.to_out[0](x)
```
这一部分对应 PyTorch 版本中的 `scaled_dot_product_attention`，而 ONNX Runtime 并没有直接实现 `scale_dot_product` 算子，只能使用最基本的 `Matmul` 操作，这也是两者性能差异最明显的地方。

总结而言，我们认为 `scaled_dot_product_attention` 是导致 PyTorch 推理速度明显优于 ONNX 的主要原因。

**Comment by Bigfishering** [comment]
非常感谢您的解答，我也在尝试优化，后续有进展再交流~

**Comment by lidingke** [comment]
onnxruntime应该是实现了sdpa的，是不是把348这行换成torch.nn.functional.scaled_dot_product_attention，再导出onnx，这个算子就能享受onnxruntime的sdpa优化了。

**Comment by DakeQQ** [comment]
@lidingke 
感谢您提供详细的代码建议。我们对比了使用 `scaled_dot_product_attention` 和普通 `MatMul` 实现的过程，以下是图表的详细信息：
很明显，ONNX Runtime 中的 `scaled_dot_product_attention` 实现本质上只是用 `MatMul` 操作以及一些小的运算符替代了原有流程。图表显示，`scaled_dot_product_attention` 中的运算符总数比我们的实现更多，因此没有理由认为它会更快。实际运行测试也证明了这一点。
总之，ONNX Runtime==1.20.1 的 `scaled_dot_product_attention` 实现只是表面上的修改，没有对底层运算符进行更深层次的优化。

`scaled_dot_product_attention`:
![Screenshot from 2024-12-11 11-08-26](https://github.com/user-attachments/assets/0f9f634c-a931-41bb-859e-406a143b9cf0)

`Ours`:
![Screenshot from 2024-12-11 11-08-49](https://github.com/user-attachments/assets/9f213495-1507-4024-b8de-3c6afd84295a)
