### ISSUE TITLE
onnxruntime已找到加速方法

### ISSUE THREAD

**Issue by Bigfishering** [DakeQQ/F5-TTS-ONNX#8]
在[onnxruntime](https://github.com/microsoft/onnxruntime/tree/main)/[onnxruntime](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime)/[python](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python)/[tools](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools)/[transformers](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers)
 这个路径下，有针对transformer的优化，可以直接将onnx输入再输出优化后的onnx，我看了有对attention的一些操作的融合，您可以研究一下

**Comment by DakeQQ** [comment]
谢谢您，我尝试了 transformers.optimizer，但 F5-TTS-ONNX 没有明显的性能提升。
